directories:
  output: release
  buildResources: build
appId: com.hotelmanagement.secure
productName: Hotel Management System
win:
  target: nsis
  icon: app-icon.ico
  artifactName: HotelManagement-Setup-${version}.${ext}
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Hotel Management
  installerIcon: app-icon.ico
  uninstallerIcon: app-icon.ico
files:
  - filter:
      - electron-main.cjs
      - preload.cjs
      - app_dist/**/*
      - dist/**/*
      - .env
asar: true
electronVersion: 38.3.0
